import Dexie, { type Table } from 'dexie';
import type { Receipt } from '../utils/types';

// Stored receipt — id is auto-generated by Dexie, all other fields match the Receipt interface.
// imageBlob holds the compressed receipt photo locally; imageUrl is the R2/cloud URL (if any).
export type StoredReceipt = Omit<Receipt, 'id'> & { id?: number };

class ScatterbrainDB extends Dexie {
  receipts!: Table<StoredReceipt, number>;

  constructor() {
    super('scatterbrain');
    this.version(1).stores({
      // Index: id (auto-increment PK), receiptDate for sorting, category for filtering
      receipts: '++id, receiptDate, category, storeName, clientName',
    });
  }
}

export const db = new ScatterbrainDB();

// ── CRUD helpers ──────────────────────────────────────────────────────────────

export async function addReceipt(data: StoredReceipt): Promise<Receipt> {
  const id = await db.receipts.add(data);
  return { ...data, id } as Receipt;
}

export async function getAllReceipts(): Promise<Receipt[]> {
  const rows = await db.receipts.orderBy('receiptDate').reverse().toArray();
  return rows as Receipt[];
}

export async function getReceiptById(id: number): Promise<Receipt | undefined> {
  return db.receipts.get(id) as Promise<Receipt | undefined>;
}

export async function updateReceipt(id: number, changes: Partial<StoredReceipt>): Promise<Receipt> {
  await db.receipts.update(id, { ...changes, updatedAt: new Date().toISOString() });
  const updated = await db.receipts.get(id);
  if (!updated) throw new Error(`Receipt ${id} not found`);
  return updated as Receipt;
}

export async function deleteReceipt(id: number): Promise<void> {
  await db.receipts.delete(id);
}

export async function getReceiptsByYear(year: number): Promise<Receipt[]> {
  const prefix = String(year);
  const rows = await db.receipts
    .where('receiptDate')
    .startsWith(prefix)
    .reverse()
    .sortBy('receiptDate');
  return rows as Receipt[];
}
